define({root:
//begin v1.x content //==en-us==//
            {
                //================================================//
                ar: "Arabic",
                cs: "Czech",
                de: "German",
                el: "Greek",
                en: "English",
                'en-au': "English (Australia)",
                'en-us-hawaii': "English (US-Hawaii)",
                'en-us-new_york-brooklyn': "English (Brooklynese)",
                'en-us-texas': "English (Texas)",
                es: "Spanish",
                fa: "Farsi",
                fr: "French",
                he: "Hebrew",
                hi: "Hindi",
                it: "Italian",
                ja: "Japanese",
                ko: "Korean",
                pl: "Polish",
                pt: "Portugese",
                ru: "Russian",
                sw: "Kiswahili",
                th: "Thai",
                tr: "Turkish",
                yi: "Yiddish",
                'zh-cn': "Chinese (Simplified)",
                'zh-tw': "Chinese (Traditional)",
                hello: "Hello",
                dojo: "Dojo",
                hello_dojo: "${hello}, ${dojo}!",
                file_not_found: "The file you requested, ${0}, is not found.",
                //==========Labels======================================//
                //-------menu----------------------//
                home: "Home",
                joinTodayMenu: "Join Today",
                emailLogin: "Email address",
                passLogin: "Password",
                signIn: "Sign In",
                showMenu: "ShowMenu",
                //-------join_Editor-------------------//
                joinToday: "Join tuShop Today",
                emailAddress: "Email Address",
                userName: "User Name",
                firstName: "First Name",
                lastName: "Last Name",
                password: "Password",
                confirm: "Confirm",
                tuShopTerms: "I agree to the tuShop Terms and Privacy.",
                joinNow: "Join Now",
                alreadyJoined: "Already on tuShop?",
                //-------join_Editor2----------------------//
                thanksForReg: "Thank you for signing with us. Please take your time to complete the following Steps.",
                userContactHeader: "User Contact",
                userStreet: "Address",
                userStreet2: "Address 2",
                userCity: "City",
                userState: "State",
                userZip: "Zip Code",
                userCountry: "Country",
                userSelectCountry: "Select Country...",
                userFax: "Fax Number",
                userUrl: "Web site",
                userPhoneDefault: "Phone 1",
                userPhone2: "Phone 2",
                userOccupation: "Occupation",
                btnContinue: "Continue",
                //-------join_Editor3----------------------//
                thanksForReg3: "Please take your time to complete this Last Step.",
                userSecurityHeader: "User Security",
                userDob: "Date of Birth",
                userSelectQuestions: "Select Questions and Fill the Answers.",
                userQuestion1: "(1) Question",
                userOptionsCaptionLabel1: "Select First Question...",
                userAnswer1: "Answer",
                userQuestion2: "(2) Question",
                userOptionsCaptionLabel2: "Select Second Question...",
                userAnswer2: "Answer",
                userEnterPin: "Enter a Four Digit PIN number that you can remember.",
                userPin: "PIN",
                btnContinue2: "Continue",
                 //-------join_Editor_Complete----------------------//
                thanksForRegComplete: "You have successfully completed your Registration. We have sent you email to your provided Email Address. Check your Email box and follow the link to confirm the Address.",
                //-------countries----------------------//
                NGA1: "Nigeria1",
                NGA2: "Nigeria2",
                NGA3: "Nigeria3",
                NGA4: "Nigeria4"
                        ///
            }



//end v1.x content
    ,
      "de": 1,
      "fr": 1
      
  /*  "zh-tw": 1,
    "zh-cn": 1,
    "yi": 1,
    "tr": 1,
    "th": 1,
    "sw": 1,
    "ru": 1,
    "pt": 1,
    "pl": 1,
    "ko": 1,
    "ja": 1,
    "it": 1,
    "hi": 1,
    "he": 1,
    "fr": 1,
     "fa": 1,
    "es": 1,
    "en-us-texas": 1,
    "en-us-new_york-brooklyn": 1,
    "en-us-hawaii": 1,
    "en-au": 1,
    "el": 1, 
    "de": 1,
    "cs": 1,
    "ar": 1 */
});
